"""
pi-agent-core: Stateful agent with tool execution, event streaming,
steering/follow-up message queuing, and proxy transport.
"""

import contextlib

# Core Agent
from .agent import Agent, AgentOptions

# Loop functions
from .agent_loop import agent_loop, agent_loop_continue

# Proxy utilities
from .proxy import ProxyAsyncStream, ProxyStreamOptions, stream_proxy

# Anthropic adapter (optional — requires `pip install pi-agent-core[anthropic]`)
with contextlib.suppress(ImportError):
    from .anthropic import stream_anthropic

# Types
from .types import (
    AgentContext,
    AgentEndEvent,
    AgentEvent,
    AgentLoopConfig,
    AgentMessage,
    AgentStartEvent,
    AgentState,
    AgentTool,
    AgentToolResult,
    AgentToolSchema,
    AgentToolUpdateCallback,
    AssistantMessage,
    AssistantMessageEvent,
    ContentBlock,
    ImageContent,
    Message,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    Model,
    SimpleStreamOptions,
    StopReason,
    StreamDoneEvent,
    StreamErrorEvent,
    StreamFn,
    StreamResult,
    StreamStartEvent,
    StreamTextDeltaEvent,
    StreamTextEndEvent,
    StreamTextStartEvent,
    StreamThinkingDeltaEvent,
    StreamThinkingEndEvent,
    StreamThinkingStartEvent,
    StreamToolCallDeltaEvent,
    StreamToolCallEndEvent,
    StreamToolCallStartEvent,
    TextContent,
    ThinkingBudgets,
    ThinkingContent,
    ThinkingLevel,
    ToolCall,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    ToolResultMessage,
    Transport,
    TurnEndEvent,
    TurnStartEvent,
    Usage,
    UsageCost,
    UserMessage,
)

__all__ = [
    "Agent",
    "AgentContext",
    "AgentEndEvent",
    "AgentEvent",
    "AgentLoopConfig",
    "AgentMessage",
    "AgentOptions",
    "AgentStartEvent",
    "AgentState",
    "AgentTool",
    "AgentToolResult",
    "AgentToolSchema",
    "AgentToolUpdateCallback",
    "AssistantMessage",
    "AssistantMessageEvent",
    "ContentBlock",
    "ImageContent",
    "Message",
    "MessageEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "Model",
    "ProxyAsyncStream",
    "ProxyStreamOptions",
    "SimpleStreamOptions",
    "StopReason",
    "StreamDoneEvent",
    "StreamErrorEvent",
    "StreamFn",
    "StreamResult",
    "StreamStartEvent",
    "StreamTextDeltaEvent",
    "StreamTextEndEvent",
    "StreamTextStartEvent",
    "StreamThinkingDeltaEvent",
    "StreamThinkingEndEvent",
    "StreamThinkingStartEvent",
    "StreamToolCallDeltaEvent",
    "StreamToolCallEndEvent",
    "StreamToolCallStartEvent",
    "TextContent",
    "ThinkingBudgets",
    "ThinkingContent",
    "ThinkingLevel",
    "ToolCall",
    "ToolExecutionEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolResultMessage",
    "Transport",
    "TurnEndEvent",
    "TurnStartEvent",
    "Usage",
    "UsageCost",
    "UserMessage",
    "agent_loop",
    "agent_loop_continue",
    "stream_anthropic",
    "stream_proxy",
]
